### ISSUE TITLE
Feature request - Don't apply dark mode to text in the Map or ui widgets

### ISSUE THREAD

**Issue by jdilger** [open-geocomputing/OEEex#10]
I noticed that when in dark mode the font color is also applied to the text in widgets and the Layer manager in the Map.  If it's possible to exclude dark mode from being applied to elements in the Map I think that would be helpful. 

Cheers,
John

Dark mode:
![image](https://user-images.githubusercontent.com/32108051/148848401-a5e3408e-17ba-4cb6-8d67-3f792762f7c5.png)
Light mode:
![image](https://user-images.githubusercontent.com/32108051/148848546-8ee07a3a-2465-4d41-93d7-5600f10140a5.png)

**Comment by mgravey** [comment]
how it's possible I never saw that. Probably I only do application during the day😆

**Comment by mgravey** [comment]
It's fixed! should be effective when the CWS accepte the version 0.94. Usually take less than 12 hours
