### ISSUE TITLE
Dark mode - Variable names in script imports are white text with a white background

### ISSUE THREAD

**Issue by jdilger** [open-geocomputing/OEEex#11]
Hello again!

I noticed that the text color for variable names in the script import section is white with a white background. Not much of an issue when you click on it, as it highlights the text, but I clicked away to edit the name and was surprised to see it seemingly disappear. 

Might look better with a dark grey text? 

thanks again for this tool.
Cheers

![image](https://user-images.githubusercontent.com/32108051/154591811-9d6a9443-1333-4f9b-a726-7c5fc6f15835.png)
![image](https://user-images.githubusercontent.com/32108051/154592027-04ce97eb-65a2-4252-ad78-3e4367e52f36.png)

**Comment by mgravey** [comment]
This was fixed. The fix will take effect when Google accept the new version.
Thanks for the report !
