### ISSUE TITLE
autoExport:true Unable to achieve

### ISSUE THREAD

**Issue by xingguangYan** [open-geocomputing/OEEex#12]
hello , i am very excited to get this Plugin.but there still some questions for me. hope you can give me some adivce.
![image](https://user-images.githubusercontent.com/87305660/163201343-80ebd7ee-3f79-4065-bc56-d79ba967a862.png)
oeel.Export.Image.toDrive({
  image:im,
  description:'computationDrive',
	region:geometry,
	scale:50,
	autoExport:true
})

thanks

**Comment by mgravey** [comment]
Can you share the script that I can have a look ?

Did you install the plugin from the Chrome store ?

Best,
Mathieu

**Comment by xingguangYan** [comment]
https://code.earthengine.google.com/6ed57e0178773576c75b2c385f0a2f07

**Comment by xingguangYan** [comment]
https://code.earthengine.google.com/e0fc5243674c177b45dc93464434354b

**Comment by mgravey** [comment]
the bug was related to the recent change in the console architecture. It's fixed in 331347f .
the new version would be online in the coming days.

**Comment by xingguangYan** [comment]
thanks,mgravey. if there any new upgrade Plugin. just let me know ,thanks again.

**Comment by xingguangYan** [comment]
thanks man . you are very cool.



---Original---
From: "Mathieu ***@***.***&gt;
Date: Thu, Apr 14, 2022 22:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-geocomputing/OEEex] autoExport:true Unable to achieve (Issue #12)




 
The new version was validate 3h ago.
 Normally your chrome should do the update to the 1.0.5 automatically.
