### ISSUE TITLE
Assets availability - warning when public

### ISSUE THREAD

**Issue by jdilger** [open-geocomputing/OEEex#9]
Hey there, 

This is an awesome extension, great work!

I am getting the popup warning of "some potential errors were detected" when I use "Get link" to share a script. I don't think I am doing anything wrong, but it's very possible. The test script I am using is a single legacy asset set to "anyone can read". Let me know if there's any other info you need.

os: windows 10
browser: chrome
asset: users/TEST/wlctest
link: https://code.earthengine.google.com/e7ecd7bdc3dfb4077dc0ae34c3c8899b

![image](https://user-images.githubusercontent.com/32108051/148845837-13f4c54a-bce0-4a33-80ad-cdd49d3c172f.png)
![image](https://user-images.githubusercontent.com/32108051/148845936-3a57affe-b52b-4fc1-b86e-c33066befb39.png)

**Comment by mgravey** [comment]
Start great😆, I don't have it on my side! 
If it's an issue to work because it always popup, you ca always disable this feature on the option page.

I will install a WM to check if it's something related to Windows version of Chrome.

**Comment by mgravey** [comment]
In fact, is clearly on my side that something is wrong (I should have the bug too).  I corrected the issue, should be solved with next version 0.94
